import pandas as pd
import plotly.graph_objects as go
import streamlit as st

import cached_db
from core import calculations, db, health, market_data

# Tooltip for the Summary of Health subheader -- the rules in one paragraph (the full
# threshold table is in core/health.py and docs/ROADMAP.md, V4.16).
HEALTH_HELP = (
    "Each measure is a green, yellow or red light against thresholds that depend on the company's "
    "sector (a supermarket's margins aren't a software company's, and a utility's debt isn't a "
    "retailer's). A group's light is the average of its measures and the overall verdict is the "
    "average of the three groups. A red group, or a company that is losing money or burning cash, "
    "is held at Mixed at best; both together make it Weak. With fewer than "
    f"{health.MIN_MEASURES} measures it is not rated."
)


# Curated rows per statement -- confirmed real yfinance row labels (see
# core/market_data.fetch_fundamentals's own docstring for the empirical check). Each
# tagged "money" (raw dollars, displayed in millions) or "eps" (already a per-share
# dollar figure -- must NOT be divided by a million alongside the rest) since these
# are the only rows this page assigns a known unit to; everything else a statement
# returns is left unformatted in the "View all line items" expander below.
INCOME_ROWS = [
    ("Total Revenue", "money"), ("Gross Profit", "money"), ("Operating Income", "money"),
    ("Net Income", "money"), ("Diluted EPS", "eps"),
]
BALANCE_ROWS = [
    ("Total Assets", "money"), ("Total Debt", "money"), ("Cash And Cash Equivalents", "money"),
    ("Stockholders Equity", "money"), ("Current Assets", "money"), ("Current Liabilities", "money"),
]
CASHFLOW_ROWS = [
    ("Operating Cash Flow", "money"), ("Capital Expenditure", "money"),
    ("Free Cash Flow", "money"), ("Cash Dividends Paid", "money"),
]

# Plain-English definitions for the curated rows above -- st.dataframe has no
# per-row tooltip the way column_config gives columns, so these render as a
# glossary caption under each statement tab's table instead.
ROW_HELP = {
    "Total Revenue": "Total sales before any costs are subtracted.",
    "Gross Profit": "Revenue minus the direct cost of producing what was sold.",
    "Operating Income": "Profit from core operations, after operating expenses but before interest and tax.",
    "Net Income": "The bottom line -- profit after every expense, interest, and tax.",
    "Diluted EPS": "Net Income divided by shares outstanding (including options/convertibles) -- profit per share.",
    "Total Assets": "Everything the company owns.",
    "Total Debt": "All interest-bearing borrowing, short- and long-term.",
    "Cash And Cash Equivalents": "Cash on hand plus assets convertible to cash almost immediately.",
    "Stockholders Equity": "Assets minus liabilities -- the owners' stake in the company.",
    "Current Assets": "Assets expected to convert to cash within a year.",
    "Current Liabilities": "Obligations due within a year.",
    "Operating Cash Flow": "Cash generated by core business operations.",
    "Capital Expenditure": "Cash spent on property, plant, and equipment.",
    "Free Cash Flow": "Operating Cash Flow minus Capital Expenditure -- cash left over after running and growing the business.",
    "Cash Dividends Paid": "Cash paid out to shareholders as dividends.",
}


def _format_cell(value, kind: str) -> str:
    if value is None or pd.isna(value):
        return "—"
    if kind == "eps":
        return f"${value:,.2f}"
    return f"${value / 1e6:,.0f}M"


def _curated_table(statement: dict, rows: list[tuple[str, str]]) -> pd.DataFrame:
    """Rows=curated labels (index), columns=[Trend, then dates ascending]. Trend
    holds each row's own raw (unformatted, same-scale-as-the-rest-of-the-page)
    values as a plain list of floats -- st.dataframe's LineChartColumn renders a
    list cell as an inline sparkline, so this needs the numbers, not the formatted
    "$X,XXXM" strings the date columns use. A missing point becomes 0.0, not None --
    confirmed the chart column silently falls back to showing the raw list as text
    if any entry is None. Placed first (right after the label column) per direct
    user request, so the shape reads before any of the numbers do. Empty when the
    statement has none of these labels at all (e.g. an ETF's empty statement)."""
    all_dates = sorted({d for label, _ in rows for d in (statement.get(label) or {})})
    if not all_dates:
        return pd.DataFrame()
    data = {label: [_format_cell((statement.get(label) or {}).get(d), kind) for d in all_dates] for label, kind in rows}
    df = pd.DataFrame(data, index=all_dates).T
    trend = {
        label: [
            (v / 1e6 if kind == "money" else v) if v is not None and not pd.isna(v) else 0.0
            for v in ((statement.get(label) or {}).get(d) for d in all_dates)
        ]
        for label, kind in rows
    }
    df.insert(0, "Trend", [trend[label] for label in df.index])
    return df


def _raw_table(statement: dict, exclude_labels: set) -> pd.DataFrame:
    """Every OTHER row the statement actually returned, in its native (unformatted)
    units -- deliberately not forced into the curated table's money/EPS formatting,
    since a raw statement mixes dollar amounts, per-share figures, share counts, and
    ratios/rates with no metadata telling this page which is which."""
    remaining = {label: values for label, values in statement.items() if label not in exclude_labels}
    if not remaining:
        return pd.DataFrame()
    all_dates = sorted({d for values in remaining.values() for d in values})
    data = {label: [values.get(d) for d in all_dates] for label, values in remaining.items()}
    return pd.DataFrame(data, index=all_dates).T


def _render_statement_tab(statement: dict, rows: list[tuple[str, str]], unit_caption: str):
    if not statement:
        st.info("No data available for this statement.")
        return
    st.caption(unit_caption)
    st.dataframe(
        _curated_table(statement, rows), use_container_width=True,
        column_config={"Trend": st.column_config.LineChartColumn("Trend", width="small")},
    )
    with st.expander("What do these line items mean?"):
        for label, _ in rows:
            st.caption(f"**{label}** -- {ROW_HELP.get(label, '')}")
    raw = _raw_table(statement, {label for label, _ in rows})
    if not raw.empty:
        with st.expander(f"View all line items ({len(raw)} more)"):
            st.caption(
                "Values as reported by Yahoo Finance, in their native units (not "
                "reformatted) -- dollar amounts, per-share figures, and share counts "
                "may appear side by side."
            )
            st.dataframe(raw, use_container_width=True)

st.title("Company Fundamentals")
with st.expander("What does this page do?"):
    st.caption(
        "Shows one holding's real income statement, balance sheet, and cash flow "
        "(annual, straight from yfinance), plus an Analyst Target valuation -- the "
        "current price compared against sell-side analysts' own real price targets, "
        "not a value this app computes itself."
    )




def _refresh_fundamentals_live(symbols: list[str]) -> int:
    """"Refresh now" button's handler -- the live-fetch-with-fallback logic, mirroring
    Monitor Stocks' own _refresh_stock_profile_live. Deliberately stays page-local
    (not promoted to cached_db.py like the DB-first read below it) -- matches this
    app's own established precedent (V4.9.3 gave rebalance.py its own local mirror
    of Monitor Stocks' refresh handler rather than sharing one). calculations.
    apply_fundamentals_fallback() replaces any row that fails THIS live attempt with
    the last real values captured in fundamentals_cache, if any. Rows that DID succeed
    live get upserted right after -- deliberately only the successful ones, so a still
    -blocked symbol never overwrites a real captured value with another blank. Busts
    cached_db.fundamentals_summary() so the very next read reflects what was just
    fetched. Returns the count of symbols that failed THIS live attempt."""
    live = market_data.fetch_fundamentals(symbols)
    cached = db.fetch_fundamentals_cache()
    merged = calculations.apply_fundamentals_fallback(live, cached)

    fresh_rows = merged[~merged["Stale"] & merged["Current Price"].notna()]
    if not fresh_rows.empty:
        db.save_fundamentals_cache(fresh_rows.drop(columns=["Stale", "Fetched At"]).to_dict("records"))

    cached_db.invalidate_fundamentals_summary()
    return int(merged["Stale"].sum())


# ---------------------------------------------------------------------------------
# Zone 1: category filter -> symbol picker (your current holdings), same category
# vocabulary and radio-filter pattern as Auto Trendline / Monitor Stocks (see
# app_pages/symbol_analysis.py's own Zone 1) -- plus a free-text search for any
# OTHER symbol, added per direct user request ("can I look up a stock I don't
# hold?"). The free-text box takes priority whenever it has something typed into
# it. No data-layer change needed for this: cached_db.fundamentals_summary()/
# market_data.fetch_fundamentals() below already resolve any valid ticker, not
# just a held one -- this is purely a second input feeding the same `symbol`.
# ---------------------------------------------------------------------------------
positions = calculations.compute_current_positions(cached_db.cached_fetch_trades())
symbol_types = cached_db.cached_fetch_symbol_types()

available = positions.merge(symbol_types, on="Symbol", how="left")
available["Allocation Type"] = available["Allocation Type"].fillna("Others")

holding_symbol = None
if available.empty:
    st.info("No current holdings to pick from -- search any symbol below instead.")
else:
    category = st.radio(
        "Filter by type", ["All", "Others", "Dividend", "Growth"],
        horizontal=True, label_visibility="collapsed", key="company_fundamentals_category_filter",
    )
    symbol_options = available if category == "All" else available[available["Allocation Type"] == category]
    if symbol_options.empty:
        st.info(f"No current holdings in the {category} category.")
    else:
        holding_symbol = st.selectbox("Symbol (your holdings)", sorted(symbol_options["Symbol"].tolist()))

free_symbol = st.text_input(
    "Or look up any other symbol", placeholder="e.g. AAPL",
    key="company_fundamentals_free_symbol",
    help="Not limited to your current holdings -- any ticker yfinance can resolve.",
).strip().upper()

symbol = free_symbol or holding_symbol
if not symbol:
    st.stop()

just_refreshed_stale = False
if st.button("Refresh now", help="Fetch the latest live data from yfinance now (normal page loads read from the database instead)."):
    just_refreshed_stale = bool(_refresh_fundamentals_live([symbol]))

profile = cached_db.fundamentals_summary([symbol])
if profile.empty:
    st.warning(f"Couldn't fetch fundamentals for {symbol}.")
    st.stop()
row = profile.iloc[0]

if just_refreshed_stale:
    st.warning(
        f"{symbol} couldn't be fetched live just now (likely a temporary yfinance/Yahoo "
        "issue) -- showing the last successfully captured values instead."
    )

st.subheader(symbol)
st.caption(f"Data last refreshed: {pd.Timestamp(row['Fetched At']).strftime('%d/%m/%Y %H:%M')}")

# ---------------------------------------------------------------------------------
# Company Profile -- straight from yfinance's own info dict (Business Summary,
# Industry, Sector, Employees, headquarters location), confirmed field-for-field
# against a real reference site's own "Company Profile" panel for BP. Skipped
# entirely, not shown as an empty section, when none of these fields are present
# (a real, valid outcome for some ETFs/funds).
# ---------------------------------------------------------------------------------
has_profile = any(
    pd.notna(row.get(field)) for field in ("Business Summary", "Industry", "Sector", "Employees", "Country")
)
if has_profile:
    prof_col, meta_col = st.columns([3, 1])
    with prof_col:
        st.subheader("Company Profile")
        if pd.notna(row.get("Business Summary")):
            st.write(row["Business Summary"])
    with meta_col:
        st.write("")  # rough vertical alignment with prof_col's subheader
        if pd.notna(row.get("Industry")):
            st.metric("Industry", row["Industry"])
        if pd.notna(row.get("Sector")):
            st.metric("Sector", row["Sector"])
        if pd.notna(row.get("Employees")):
            st.metric("Employees", f"{int(row['Employees']):,}")
        market = ", ".join(v for v in (row.get("City"), row.get("Country")) if pd.notna(v))
        if market:
            st.metric("Market", market)

# Generic currency/financialCurrency comparison -- fires for ANY holding with the
# mismatch (confirmed real for TSM: USD quote, TWD statements), not a TSM special case.
# pd.notna(), not plain truthiness: a genuinely absent Financial Currency (every ETF)
# reads back from a multi-row query as float NaN, not Python None -- and NaN is
# truthy, so `if row["Financial Currency"]` would have fired this banner on nearly
# every ETF holding (confirmed against real dev data: 24 of the portfolio's 27 ETFs).
if pd.notna(row["Currency"]) and pd.notna(row["Financial Currency"]) and row["Currency"] != row["Financial Currency"]:
    st.warning(
        f"Statements reported in {row['Financial Currency']}, quote priced in {row['Currency']}. "
        "Per-share figures and raw statement totals below aren't directly comparable to "
        "the trading price without a currency conversion."
    )

income = row["Income Statement"]
balance = row["Balance Sheet"]
cashflow = row["Cash Flow"]

# ---------------------------------------------------------------------------------
# Summary of Health (V4.16) -- a rule-of-thumb read of the stored annual statements,
# from core/health.py (shared with Monitor Stocks' Health column and the Hermes MCP
# server, so all three show the same verdict). Nothing here is fetched or saved. An
# ETF/fund has no statements, so assess_health() returns None and the section is
# simply absent (the "no financial statements" note below covers that case).
# ---------------------------------------------------------------------------------
health_result = health.assess_health(income, balance, cashflow, row.get("Sector"), row.get("Industry"))
if health_result is not None:
    st.subheader("Summary of Health", help=HEALTH_HELP)
    if health_result["overall"] is None:
        n_measures = health_result["n_measures"]
        st.info(
            f"Not enough data to rate -- only {n_measures} usable measure{'s' if n_measures != 1 else ''} "
            f"in the stored statements (at least {health.MIN_MEASURES} needed)."
        )
    else:
        st.markdown(f"**Overall: {health.format_health_cell(health_result)}**")

    for col, group in zip(st.columns(3), health.GROUPS):
        group_result = health_result["groups"][group]
        with col:
            st.markdown(f"**{health.DOTS.get(group_result['light'], '⚪')} {group}**")
            if group_result["measures"]:
                st.markdown("  \n".join(
                    f"{health.DOTS[m['light']]} {m['name']}: {m['value']}" for m in group_result["measures"]
                ))
            else:
                st.caption("Not rated for this kind of statement.")

    reasons = health.health_reasons(health_result)
    if reasons:
        st.markdown("**Watch:** " + "; ".join(reasons))
    elif health_result["overall"] == health.YELLOW:
        st.markdown("No single red measure -- the verdict reflects several middling readings.")

    caption = (
        "A rule-of-thumb read of the latest stored annual statements "
        f"({health.PROFILE_DESCRIPTIONS[health_result['profile']]}), not investment advice."
    )
    if health_result["partial"]:
        caption += " These statements look like a bank, lender or fund, so it is rated on return on equity and growth only."
    st.caption(caption)

# ---------------------------------------------------------------------------------
# Valuation card -- Analyst Target is real yfinance data (targetMeanPrice, an
# aggregate of real sell-side analysts' own price targets), not something this app
# calculates; the only original work here is the plain % comparison against the
# current price and the Overvalued/Undervalued/Fair value labeling (>+2%/<-2%/between).
# ---------------------------------------------------------------------------------
st.subheader("Valuation — Analyst Target")
current_price = row["Current Price"]
target = row["Target Mean Price"]
assessment = calculations.valuation_assessment(current_price, target)
if assessment["verdict"] == "No coverage":
    st.info("No analyst coverage.")
else:
    pct = assessment["pct"]
    verdict = assessment["verdict"]
    # pd.notna(), not plain truthiness -- int(float("nan")) raises, and a NaN read
    # back from a multi-row query is truthy, so a bare `if row[...]` wouldn't even
    # catch it before the crash.
    analysts = int(row["Number Of Analysts"]) if pd.notna(row["Number Of Analysts"]) else 0

    vcol1, vcol2, vcol3 = st.columns(3)
    vcol1.metric("Current Price", f"${current_price:,.2f}")
    vcol2.metric(
        "Analyst Target (mean)", f"${target:,.2f}", delta=f"{pct:+.1f}%", delta_color="inverse",
        help=(
            "The average 12-month price target from real sell-side analysts covering "
            "this stock, as aggregated by Yahoo Finance -- not a value this app "
            "calculates itself."
        ),
    )
    vcol3.metric(
        verdict, f"{analysts} analyst{'s' if analysts != 1 else ''}",
        help="Overvalued if Current Price is >2% above the target, Undervalued if >2% below, Fair value in between.",
    )

# Confirmed real (see fetch_fundamentals's own docstring): an ETF's income_stmt/
# balance_sheet/cashflow are all genuinely empty DataFrames, not a fetch failure --
# nothing below (KPI row, ratios, chart, statement tabs) has anything to compute from.
if not income and not balance and not cashflow:
    st.info("No financial statements available for this symbol (likely an ETF or fund).")
    st.stop()


def _kpi_card(col, label: str, dates: list, values: list, delta_color: str, help_text: str):
    """One KPI card: latest value (in millions), its YoY delta, and a sparkline
    across every year available -- the mockup's own "Revenue/Net Income/FCF/Total
    Debt" row, ported here almost directly since it's just a compact restatement of
    data the Overview tab's own chart already fetches. `delta_color="inverse"` for
    Total Debt (a decrease is the good direction), "normal" for the other three (an
    increase is)."""
    with col:
        latest = values[-1] if values else None
        value_text = f"${latest / 1e6:,.0f}M" if latest is not None and not pd.isna(latest) else "N/A"
        pct = calculations.yoy_pct(values)
        st.metric(
            label, value_text,
            delta=f"{pct:+.1f}% YoY" if pct is not None else None,
            delta_color=delta_color, help=help_text,
        )
        if len(values) > 1:
            # Indexed by year only (dates[:4]) -- the full "YYYY-MM-DD" period-end
            # date was correct but needlessly precise for a sparkline axis; the day
            # is always the fiscal year-end anyway, so the year alone is the whole
            # meaningful part. height=150 (up from an original 60 matching the
            # mockup) so the year-to-year shape is actually legible.
            series = pd.Series(
                [v / 1e6 if v is not None and not pd.isna(v) else 0 for v in values],
                index=[d[:4] for d in dates],
            )
            st.bar_chart(series, height=150, use_container_width=True)


kcol1, kcol2, kcol3, kcol4 = st.columns(4)
_kpi_card(kcol1, "Revenue (latest FY)", *calculations.statement_series(income, "Total Revenue"), "normal",
          "Total sales in the most recent fiscal year, before any costs are subtracted.")
_kpi_card(kcol2, "Net Income (latest FY)", *calculations.statement_series(income, "Net Income"), "normal",
          "Bottom-line profit in the most recent fiscal year, after every expense, interest, and tax.")
_kpi_card(kcol3, "Free Cash Flow (latest FY)", *calculations.statement_series(cashflow, "Free Cash Flow"), "normal",
          "Cash left over after operating and capital expenses in the most recent fiscal year.")
_kpi_card(kcol4, "Total Debt (latest FY)", *calculations.statement_series(balance, "Total Debt"), "inverse",
          "All interest-bearing borrowing outstanding at the most recent fiscal year-end.")

tab_overview, tab_income, tab_balance, tab_cashflow = st.tabs(
    ["Overview", "Income Statement", "Balance Sheet", "Cash Flow"]
)

with tab_overview:
    # calculations.compute_key_ratios() (V4.15) -- shared with the Hermes MCP server's
    # get_company_fundamentals tool. A ratio is None (rendered "N/A") rather than an
    # error when a line item is missing -- e.g. a company with no captured Stockholders
    # Equity this year.
    st.subheader("Key ratios")
    ratios = calculations.compute_key_ratios(income, balance)
    gross_margin, op_margin = ratios["gross_margin"], ratios["operating_margin"]
    roe, debt_equity, current_ratio = ratios["return_on_equity"], ratios["debt_to_equity"], ratios["current_ratio"]

    rcol1, rcol2, rcol3, rcol4, rcol5 = st.columns(5)
    rcol1.metric(
        "Gross Margin", f"{gross_margin * 100:.1f}%" if gross_margin is not None else "N/A",
        help="Gross Profit as a % of Revenue -- how much is left after the direct cost of what was sold.",
    )
    rcol2.metric(
        "Operating Margin", f"{op_margin * 100:.1f}%" if op_margin is not None else "N/A",
        help="Operating Income as a % of Revenue -- profitability from core operations, before interest and tax.",
    )
    rcol3.metric(
        "Return on Equity", f"{roe * 100:.1f}%" if roe is not None else "N/A",
        help="Net Income as a % of Stockholders Equity -- how efficiently shareholders' capital is turned into profit.",
    )
    rcol4.metric(
        "Debt / Equity", f"{debt_equity:.2f}x" if debt_equity is not None else "N/A",
        help="Total Debt divided by Stockholders Equity -- how leveraged the company is. Higher means more reliance on borrowing.",
    )
    rcol5.metric(
        "Current Ratio", f"{current_ratio:.2f}x" if current_ratio is not None else "N/A",
        help="Current Assets divided by Current Liabilities -- ability to cover short-term obligations. Above 1x is generally healthy.",
    )

    # Revenue / Net Income trend -- every year the income statement actually
    # returned, not just the latest. Raw yfinance values are absolute dollars
    # (confirmed: MSFT's latest Total Revenue is ~3.3e11, not pre-scaled) --
    # divided by 1e6 here so the axis reads in millions, matching the statement
    # tables' own unit below. Plotly's graph_objects (not express) for the mixed
    # bar+line trace -- this app already depends on Plotly via Monitor Stocks'
    # plotly.express usage.
    rev_dates, rev_values = calculations.statement_series(income, "Total Revenue")
    _, ni_values = calculations.statement_series(income, "Net Income")
    if rev_dates:
        fig = go.Figure()
        fig.add_bar(x=rev_dates, y=[v / 1e6 if v is not None else None for v in rev_values], name="Revenue")
        fig.add_scatter(
            x=rev_dates, y=[v / 1e6 if v is not None else None for v in ni_values],
            name="Net Income", mode="lines+markers",
        )
        fig.update_layout(
            height=320, margin=dict(t=20, b=20, l=10, r=10),
            legend=dict(orientation="h", yanchor="bottom", y=1.02),
            yaxis_title="USD, millions",
        )
        st.plotly_chart(fig, use_container_width=True)

with tab_income:
    _render_statement_tab(income, INCOME_ROWS, "USD, millions (Diluted EPS in dollars/share)")

with tab_balance:
    _render_statement_tab(balance, BALANCE_ROWS, "USD, millions")

with tab_cashflow:
    _render_statement_tab(cashflow, CASHFLOW_ROWS, "USD, millions")
